- name: download and install jd for doing JSON diff
  become: true
  get_url:
      url: https://github.com/josephburnett/jd/releases/download/v1.1/jd
      dest: /usr/local/bin
      mode: 0555

- name: install the jq command for command-line processing and printing of JSON files
  become: true
  apt:
      name:
        - jq
