---

- name: install Bash command-line utilities
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: install command-line utilities
    apt:
        name:
          - curl
          - tree
          - unzip
        update_cache: yes
        state: latest

