---

- name: install and configure git
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: install git
    become: yes
    apt:
        name: git
        update_cache: yes
        state: latest

  - name: configure global git settings
    shell: |
      git config --global user.email "tmcphillips@absoluteflow.com"
      git config --global user.name "Timothy McPhillips"
      git config --global core.fileMode false                       # ignore file permission changes in local clone
      git config --global core.eol lf                               # force all line-endings to LF on checkout
      git config --global core.autocrlf input                       # convert CRLF line-endings to LF on commit
