---

- name: install OpenJDK 8 JDK
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  
  - name: install openjdk-8-jdk
    apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: latest

