---

- name: install Terraform
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  
  - name: insure unzip is installed
    apt:
        name: unzip
        update_cache: yes
        state: latest

  - name: download and expand terraform binary
    unarchive:
        remote_src: yes
        src: https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
        dest: /usr/local/bin
