---

- name: install python3
  become: yes
  apt:
      name: python3
      update_cache: yes
      state: latest

- name: install pip for python3
  become: yes
  apt:
      name: python3-pip
      update_cache: yes
      state: latest

- name: upgrade pip3 to latest version
  become: yes
  command: pip3 install -U pip

- name: install venv for python3
  become: yes
  apt:
      name: python3-venv
      update_cache: yes
      state: latest
