---

- name: work with OpenRefine provenance project
  hosts: 127.0.0.1
  connection: local
  roles:
#    - git
#    - jdk8
#    - json-cli-tools
#    - openrefine
#    - python3
    - openrefine-prov
