---

- name: clone the openrefine-provenance Git repo
  git:
      repo: git@github.com:tmcphillips/openrefine-provenance
      dest: ~/GitRepos/openrefine-provenance

- name: create Python3 virtual environment for installing Jupyter
  shell: python3 -m venv ~/GitRepos/openrefine-provenance/.venv-or-prov --system-site-packages

# the next step is necessary when using Python 3.5 because pip is not bundled with Python
- name: install pip3 in virtual environment
  shell: |
    curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
    . ~/GitRepos/openrefine-provenance/.venv-or-prov/bin/activate
    python /tmp/get-pip.py

- name: install jupyter into the virtual environment
  pip:
    name: jupyter
    virtualenv: ~/GitRepos/openrefine-provenance/.venv-or-prov

- name:
  shell: |
    . ~/GitRepos/openrefine-provenance/.venv-or-prov/bin/activate
    PATH=$PATH:/usr/local/go/bin python ~/go/src/github.com/yunabe/lgo/bin/install_kernel
    deactivate
